# Generated by Django 4.2.3 on 2023-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('kind', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], default='cat', max_length=5)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('png', 'PNG'), ('gif', 'GIF'), ('jpg', 'JGP'), ('jpeg', 'JPEG')], default='png', max_length=5)),
            ],
        ),
    ]
