# Generated by Django 4.2.3 on 2023-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='avg_score',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
