# Generated by Django 4.2.3 on 2023-07-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_diary_avg_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page_count', models.IntegerField(max_length=100)),
                ('students', models.ManyToManyField(related_name='Books', to='school.student')),
            ],
        ),
    ]
